### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by addyosmani** [vuejs-templates/pwa#11]
**Where should this live?**

@yyx990803 Do we want to keep the PWA template on the vuejs org or on the templates org? 

**What do we want the template package to be called?**

`vue-cli-template-pwa`?

**Where should we call out the template on the Vue site?**

Should we add an extra note to https://vuejs.org/v2/guide/installation.html#CLI saying this is available or would a dedicated PWA page on the Vue site be better?

cc @sdras in case she has any thoughts on this too.

**Comment by sdras** [comment]
Personally, I think this is an amazing resource and should be highlighted in as many places as possible- I would love it to be in the installation guide. 

`vue-cli-template-pwa` makes sense but I think template is implied in cli, so perhaps `vue-cli-pwa` would be cleaner and easier to remember.

Exciting! Great work! 🌟

**Comment by yyx990803** [comment]
I'm on vacation this week - will be working on some CLI polishing after getting back and figure out what to do next :)

**Comment by stephane** [comment]
Do you think it's possible to extend the `webpack` template with this template features to offer two new options at init time?

1. manifest file
2. SW precache

**Comment by addyosmani** [comment]
Evan and I had a productive call about next steps yesterday (including adding these features into the default template).

For the short term we're going to keep this template separate but explore how we can make the default template output a PWA during the summer. 

Evan is going to move this repo over to the templates organization, look at any further changes that need to be made and we'll then look at releasing.

**Comment by CharlesOkwuagwu** [comment]
@addyosmani how can we use this template today? These steps below from https://github.com/vuejs/pwa#usage don't exactly tell us how to use this PWA template

$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev

**Comment by addyosmani** [comment]
It is not yet released/ready. Give it a little more time to complete moving
it over to Webpack templates organization and flesh out docs.

**Comment by nitradesign** [comment]
@CharlesOkwuagwu You can download the repository zip to your PC. Unzip the folder and then run 
vue init /path/to/downloaded/folder my-project 
This worked for me to try it out, got a 94 lighthouse score on a server with https.

**Comment by CharlesOkwuagwu** [comment]
Thanks

**Comment by CharlesOkwuagwu** [comment]
@nitradesign it gives this:

 ERROR  Failed to compile with 1 errors                                                                                                                                                                  3:04:57 PM

Module build failed: Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'
Referenced from: C:\learn\vue\demo\.eslintrc.js
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (C:\learn\vue\demo\node_modules\eslint\lib\config\plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (C:\learn\vue\demo\node_modules\eslint\lib\config\plugins.js:162:21)
    at load (C:\learn\vue\demo\node_modules\eslint\lib\config\config-file.js:541:21)
    at configExtends.reduceRight (C:\learn\vue\demo\node_modules\eslint\lib\config\config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (C:\learn\vue\demo\node_modules\eslint\lib\config\config-file.js:408:28)
    at Object.load (C:\learn\vue\demo\node_modules\eslint\lib\config\config-file.js:566:22)
    at loadConfig (C:\learn\vue\demo\node_modules\eslint\lib\config.js:63:33)
    at getLocalConfig (C:\learn\vue\demo\node_modules\eslint\lib\config.js:130:29)
    at Config.getConfig (C:\learn\vue\demo\node_modules\eslint\lib\config.js:260:26)
    at processText (C:\learn\vue\demo\node_modules\eslint\lib\cli-engine.js:224:33)
    at CLIEngine.executeOnText (C:\learn\vue\demo\node_modules\eslint\lib\cli-engine.js:754:26)
    at lint (C:\learn\vue\demo\node_modules\eslint-loader\index.js:211:17)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://localhost:8080

**Comment by CodinCat** [comment]
vue-cli does support any template on GitHub. You can initiate a project by this command now:

```sh
vue init vuejs/pwa my-project
```

**Comment by addyosmani** [comment]
Now that the template has been officially launched, we're going to close this issue up. Please feel free to file bugs for any specific behavior that isn't working as expected.
