### ISSUE TITLE
ENOVERSIONS on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by sohailalam2** [vuejs-templates/pwa#146]
I am running Ubuntu shell on Windows 10 (Windows Subsystem for Linux) and `npm install` fails with the following error - 

```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise
```

The log file shows the following (_truncated_)

```
4928 silly resolveWithNewModule url-parse-lax@1.0.0 checking installable status
4929 silly pacote range manifest for unzip-response@^1.0.2 fetched in 19ms
4930 silly resolveWithNewModule unzip-response@1.0.2 checking installable status
4931 verbose type range
4932 verbose stack timed-out: No valid versions available for timed-out
4932 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:19:11)
4932 verbose stack     at fetchPackument.then.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
4932 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
4932 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
4932 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
4932 verbose stack     at Promise._settlePromiseCtx (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
4932 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
4932 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
4932 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
4932 verbose stack     at runCallback (timers.js:773:18)
4932 verbose stack     at tryOnImmediate (timers.js:734:5)
4932 verbose stack     at processImmediate [as _immediateCallback] (timers.js:711:5)
4933 verbose cwd /mnt/d/workspace/myapp/web
4934 verbose Linux 4.4.0-43-Microsoft
4935 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
4936 verbose node v9.3.0
4937 verbose npm  v5.5.1
4938 error code ENOVERSIONS
4939 error No valid versions available for timed-out
4940 verbose exit [ 1, true ]
```

**Comment by jeffposnick** [comment]
This sounds very much like http://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018

Please let us know if you're still seeing issues today and we'll reopen and investigate further.
